---
title: "Simple Model"
output: html_notebook
---

```{r setup}
# Packages ----
library(tidyverse)
library(sparklyr)
```

```{r spark-connection}
sc <- spark_connect(method = "qubole")
```

## Data
https://spark.rstudio.com/mlib/#examples
```{r}
iris_tbl <- copy_to(sc, iris, "iris", overwrite = TRUE)
iris_tbl
```

## K means
```{r}
kmeans_model <- iris_tbl %>%
  ml_kmeans(Species ~ ., k = 3)
```

```{r}
ml_predict(kmeans_model) %>%
  collect() %>%
  ggplot(aes(Petal_Length, Petal_Width)) +
  geom_point(aes(Petal_Width, Petal_Length, col = factor(prediction + 1)),
             size = 2, alpha = 0.5) + 
  geom_point(data = kmeans_model$centers, aes(Petal_Width, Petal_Length),
             col = scales::muted(c("red", "green", "blue")),
             pch = 'x', size = 12) +
  scale_color_discrete(name = "Predicted Cluster",
                       labels = paste("Cluster", 1:3)) +
  labs(
    x = "Petal Length",
    y = "Petal Width",
    title = "K-Means Clustering",
    subtitle = "Spark overkill"
  )
```


## Linear Regression
```{r}
lm_model <- iris_tbl %>%
  select(Petal_Width, Petal_Length) %>%
  ml_linear_regression(Petal_Length ~ Petal_Width)
```

```{r}
lm_model
```

```{r}
iris_tbl %>%
  select(Petal_Width, Petal_Length) %>%
  collect %>%
  ggplot(aes(Petal_Length, Petal_Width)) +
    geom_point(aes(Petal_Width, Petal_Length), size = 2, alpha = 0.5) +
    geom_abline(aes(slope = coef(lm_model)[["Petal_Width"]],
                    intercept = coef(lm_model)[["(Intercept)"]]),
                color = "red") +
  labs(
    x = "Petal Width",
    y = "Petal Length",
    title = "Linear Regression: Petal Length ~ Petal Width",
    subtitle = "Use Spark.ML linear regression to predict petal length as a function of petal width."
  )
```

## PCA
```{r}
pca_model <- iris_tbl %>%
  select(-Species) %>%
  ml_pca()
```

```{r}
pca_model
```

## Random Forest
```{r}
rf_model <- iris_tbl %>%
  ml_random_forest(Species ~ Petal_Length + Petal_Width, type = "classification")
```

```{r}
rf_model
```


```{r}
rf_predict <- ml_predict(rf_model, iris_tbl) %>%
  ft_string_indexer("Species", "Species_idx") %>%
  collect()
table(rf_predict$Species_idx, rf_predict$prediction)
```